version: '3.8'

services:
  # Backend Node.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: generador-backend
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - AI_ENV=home
      - AI_API_URL_HOME=https://jarvis.ieshlanz.es
      - AI_MODEL=mistral:instruct
      - PORT=3005
    networks:
      - app-network
    volumes:
      - ./backend/preguntas.db:/app/preguntas.db
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
