version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: generador-preguntas
    ports:
      - "1212:3005"
    environment:
      - NODE_ENV=production
      - AI_ENV=home
      - AI_API_URL_HOME=https://jarvis.ieshlanz.es
      - AI_MODEL=mistral:instruct
      - PORT=3005
    networks:
      - app-network
    volumes:
      - ./backend/db/preguntas.db:/app/backend/db/preguntas.db
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
